# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-KRXYpWpiWMo6dybJpzRU91PzmAxvmq-
"""

from abc import ABC, abstractmethod
from typing import Dict, Type, Any

class PaymentMethod(ABC):
    @abstractmethod
    def get_details(self) -> str:
        pass
    @abstractmethod
    def pay(self, amount: float) -> bool:
        pass

class RazorpayCardPayment(PaymentMethod):
    def __init__(self, card_number: str, **kwargs: Any):
        self.card_number = card_number
    def get_details(self) -> str:
        return f"Razorpay Card (****-{self.card_number[-4:]})"
    def pay(self, amount: float) -> bool:
        print(f"Processing Razorpay Card payment of ${amount:.2f}")
        return True

class RazorpayUPIPayment(PaymentMethod):
    def __init__(self, upi_id: str, **kwargs: Any):
        self.upi_id = upi_id
    def get_details(self) -> str:
        return f"Razorpay UPI ({self.upi_id})"
    def pay(self, amount: float) -> bool:
        print(f"Processing Razorpay UPI payment of ${amount:.2f}")
        return True

class StripeCardPayment(PaymentMethod):
    def __init__(self, card_number: str, **kwargs: Any):
        self.card_number = card_number
    def get_details(self) -> str:
        return f"Stripe Card (****-{self.card_number[-4:]})"
    def pay(self, amount: float) -> bool:
        print(f"Processing Stripe Card payment of ${amount:.2f}")
        return True

class StripeUPIPayment(PaymentMethod):
    def __init__(self, upi_id: str, **kwargs: Any):
        self.upi_id = upi_id
    def get_details(self) -> str:
        return f"Stripe UPI ({self.upi_id})"
    def pay(self, amount: float) -> bool:
        print(f"Processing Stripe UPI payment of ${amount:.2f}")
        return True

class FactoryPaymentMethod(ABC):
    factory: Dict[str, Type[PaymentMethod]] = {}
    @classmethod
    def get_payment_object(cls, method_type: str, **kwargs: Any) -> PaymentMethod:
        if method_type.lower() not in cls.factory:
            raise ValueError("Invalid payment method")
        return cls.factory[method_type.lower()](**kwargs)

class RazorpayFactory(FactoryPaymentMethod):
    factory = {"card": RazorpayCardPayment, "upi": RazorpayUPIPayment}

class StripeFactory(FactoryPaymentMethod):
    factory = {"card": StripeCardPayment, "upi": StripeUPIPayment}

class Aggregator(ABC):
    def __init__(self, name: str, fee: float):
        self.name = name
        self.fee = fee
    @abstractmethod
    def get_factory(self) -> Type[FactoryPaymentMethod]:
        pass
    def call_get_payment_object(self, method_type: str, amount: float, **kwargs: Any) -> bool:
        fac = self.get_factory()
        try:
            obj = fac.get_payment_object(method_type, **kwargs)
        except ValueError as e:
            print(e)
            return False
        total = amount * (1 + self.fee / 100)
        print(f"Aggregator: {self.name} | Details: {obj.get_details()} | Total: ${total:.2f}")
        return obj.pay(total)

class RazorpayAggregator(Aggregator):
    def __init__(self):
        super().__init__("Razorpay", 2.0)
    def get_factory(self) -> Type[FactoryPaymentMethod]:
        return RazorpayFactory

class StripeAggregator(Aggregator):
    def __init__(self):
        super().__init__("Stripe", 2.9)
    def get_factory(self) -> Type[FactoryPaymentMethod]:
        return StripeFactory

class AggregatorFactory:
    factory = {"stripe": StripeAggregator, "razorpay": RazorpayAggregator}
    @classmethod
    def get_aggregator_object(cls, aggregator_name: str) -> Aggregator:
        if aggregator_name.lower() not in cls.factory:
            raise ValueError("Invalid aggregator")
        return cls.factory[aggregator_name.lower()]()

def main():
    agg_name = input("Enter aggregator (stripe/razorpay): ").strip()
    try:
        agg = AggregatorFactory.get_aggregator_object(agg_name)
    except ValueError as e:
        print(e)
        return

    method = input("Enter method (card/upi): ").strip()
    kwargs = {}
    if method == "card":
        kwargs["card_number"] = input("Enter card number: ").strip()
    elif method == "upi":
        kwargs["upi_id"] = input("Enter UPI ID: ").strip()
    else:
        print("Invalid method")
        return

    try:
        amount = float(input("Enter amount: ").strip())
    except ValueError:
        print("Invalid amount")
        return

    success = agg.call_get_payment_object(method, amount, **kwargs)
    if success:
        print("Transaction Successful")
    else:
        print("Transaction Failed")

if __name__ == "__main__":
    main()